# Generated by Django 5.2.7 on 2025-11-12 07:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0005_alter_order_items_order_alter_order_items_product'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='delivery_status',
            field=models.TextField(default='Pending'),
        ),
    ]
